name: CI/CD for PDF Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Clean npm cache
      run: npm cache clean --force
      working-directory: boletas/pdf-service

    - name: Install dependencies
      run: npm install
      working-directory: boletas/pdf-service

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Package service
      run: npx serverless package
      working-directory: boletas/pdf-service

    - name: Deploy service
      run: npx serverless deploy
      working-directory: boletas/pdf-service
